### PR TITLE
multi-node setup instructions

### PR DESCRIPTION
**Pull request by SwaroopH**
This is an older branch and the https://github.com/PowerLoom/docs/pull/17 was never merged, let's review this in detail with latest instructions and merge this please

### CODE REVIEW

**Comment by havealakshya** [comment]
fixed sentences & updated the multi-node section under getting started

**Comment by kanikamishra** [comment]
Looks good. LGTM

**Comment by kanikamishra** [comment]
Looks good, LGTM

**Review by kanikamishra — APPROVED** [review]
Looks good. LGTM!

**Pull request merged**
