### PR TITLE
Feat/aave use case

### PR DESCRIPTION
**Pull request by Seth-Schmidt**
#22

Fixes #

### Checklist
- [x] My branch is up-to-date with upstream/main branch.
- [x] Everything works and tested for major version of Python/NodeJS/Go and above.
- [x] I ran pre-commit checks against my changes.
- [x] I've written tests against my changes and all the current present tests are passing.

### Current behaviour
Docs currently don't have any information on Aave V3 use case

### New expected behaviour
Docs will have Aave V3 overview and data points in the Existing Implementations section 

#### Added

- Aave V3 implementation overview index
- Aave V3 data point breakdown
- Additional references to Aave use case in data sources and architecture sections
- Deployment and extension instructions

#### Fixed
- grammatical errors in Uniswap V2 data points section
- minor changes to Uniswap V2 Closer Look at Snapshots section

### CODE REVIEW

**Comment by SwaroopH** [comment]
Deployed on: https://powerloom-docs-245iq.ondigitalocean.app/docs/build-with-powerloom/use-cases/existing-implementations/aavev3-dashboard/

**Review by anomit — APPROVED** [review]
LGTM

**Review by kanikamishra — APPROVED** [review]
LGTM

**Review by havealakshya — APPROVED** [review]
LGTM

**Pull request merged**
